Lots of changes

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -13,10 +13,25 @@ if ! git diff --exit-code; then
     exit 1
 fi
 
-# Run all tests (UI and DB are combined in the main test script)
+# Reset and migrate database
+pnpm run db:reset
+if [ $? -ne 0 ]; then
+    echo "Database reset/migration failed. Please fix errors before committing."
+    exit 1
+fi
+
+# Run UI Tests
 pnpm run test
 if [ $? -ne 0 ]; then
     echo "Tests failed. Please fix errors before committing."
+    exit 1
+fi
+
+# Run database tests. They have to go after the UI because they change the seed
+# data.
+pnpm run db:test
+if [ $? -ne 0 ]; then
+    echo "Database tests failed. Please fix errors before committing."
     exit 1
 fi
 
